import { StyleSheet } from 'react-native';
import type { AppColors } from '../../theme/colors';
import { ACTION_ARC_H, ACTION_ARC_W, ACTION_CIRCLE_SIZE } from './constants';

export function createArenaStyles(colors: AppColors) {
    return StyleSheet.create({

  root: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  hud: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
    paddingVertical: 4,
    minHeight: 40,
  },
  hudPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.35)',
    backgroundColor: 'rgba(15, 23, 42, 0.82)',
  },
  hudPillPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.98 }],
  },
  hudExitPill: {
    borderColor: 'rgba(248, 113, 113, 0.45)',
    backgroundColor: 'rgba(127, 29, 29, 0.55)',
  },
  hudExitText: {
    color: '#fef2f2',
    fontWeight: '800',
    fontSize: 11,
    letterSpacing: 0.2,
  },
  hudCenterCluster: {
    flex: 1,
    alignItems: 'center',
    gap: 6,
    paddingTop: 2,
  },
  hudRightCluster: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 1,
    justifyContent: 'flex-end',
  },
  hudKdRow: {
    flexDirection: 'row',
    gap: 6,
  },
  hudKdPill: {
    minWidth: 44,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  hudKdLabel: {
    color: '#e2e8f0',
    fontSize: 9,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  hudKdValue: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.45)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  hudClockPill: {
    alignItems: 'center',
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderColor: 'rgba(56, 189, 248, 0.4)',
    backgroundColor: 'rgba(8, 47, 73, 0.72)',
  },
  hudPracticePill: {
    borderColor: 'rgba(167, 139, 250, 0.45)',
    backgroundColor: 'rgba(76, 29, 149, 0.45)',
  },
  hudPracticeText: {
    color: '#e9d5ff',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  hudDevPill: {
    borderColor: colors.borderStrong,
    backgroundColor: 'rgba(30, 41, 59, 0.88)',
  },
  hudDevText: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  hudResetPill: {
    borderColor: 'rgba(148, 163, 184, 0.4)',
    backgroundColor: 'rgba(30, 41, 59, 0.78)',
  },
  hudResetText: {
    color: colors.text,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  hudPhase: {
    color: '#7dd3fc',
    fontSize: 9,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
    textAlign: 'center',
  },
  hudClock: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
    textAlign: 'center',
  },
  hudOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 30,
    pointerEvents: 'box-none',
  },
  arenaFlex: {
    flex: 1,
    overflow: 'visible',
    position: 'relative',
  },
  resultsOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 90,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  venuePvpHoldOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 95,
    backgroundColor: 'rgba(0, 0, 0, 0.62)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  venuePvpHoldCard: {
    width: '100%',
    maxWidth: 380,
    borderRadius: 16,
    paddingVertical: 22,
    paddingHorizontal: 18,
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.borderStrong,
    gap: 12,
  },
  venuePvpHoldTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  venuePvpHoldBody: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 20,
  },
  venuePvpHoldBtn: {
    marginTop: 4,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: '#a78bfa',
  },
  venuePvpHoldBtnText: {
    color: colors.textInverse,
    fontSize: 15,
    fontWeight: '900',
  },
  resultsCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 18,
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.borderStrong,
    gap: 10,
  },
  resultsTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  resultsSubtitle: {
    marginTop: 2,
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    textAlign: 'center',
  },
  resultsTable: {
    marginTop: 4,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.borderStrong,
  },
  resultsTableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 10,
    backgroundColor: colors.bgElevated,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  resultsTableHeaderRow: {
    paddingVertical: 8,
    backgroundColor: colors.surface,
  },
  resultsTableRowLast: {
    borderBottomWidth: 0,
  },
  resultsTh: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  resultsTd: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '800',
  },
  resultsColName: {
    flex: 1,
    minWidth: 0,
    paddingRight: 6,
  },
  resultsColStat: {
    width: 28,
    textAlign: 'center',
  },
  resultsColXp: {
    width: 44,
    textAlign: 'right',
    fontVariant: ['tabular-nums'],
  },
  resultsColResult: {
    width: 52,
    textAlign: 'right',
    fontSize: 11,
    fontWeight: '900',
    color: colors.textSecondary,
  },
  resultsBtn: {
    marginTop: 6,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: '#a78bfa',
  },
  resultsBtnPressed: { opacity: 0.9 },
  resultsBtnText: {
    color: colors.textInverse,
    fontSize: 15,
    fontWeight: '900',
  },
  devPanelOverlay: {
    position: 'absolute',
    left: 12,
    right: 12,
    top: 54,
    zIndex: 80,
  },
  devPanel: {
    padding: 12,
    borderRadius: 14,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.borderStrong,
  },
  devRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  devLabel: {
    flex: 1,
    color: colors.text,
    fontSize: 12,
    fontWeight: '900',
  },
  devChip: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
    minWidth: 88,
    alignItems: 'center',
  },
  devChipOn: {
    backgroundColor: 'rgba(34, 197, 94, 0.14)',
    borderColor: 'rgba(34, 197, 94, 0.45)',
  },
  devChipOff: {
    backgroundColor: 'rgba(148, 163, 184, 0.10)',
    borderColor: 'rgba(148, 163, 184, 0.25)',
  },
  devChipPressed: { opacity: 0.88 },
  devChipText: {
    color: colors.text,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  devStepper: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  devStepBtn: {
    width: 34,
    height: 28,
    borderRadius: 10,
    backgroundColor: colors.bgElevated,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  devStepBtnPressed: { opacity: 0.85 },
  devStepBtnText: { color: colors.text, fontSize: 16, fontWeight: '900' },
  devValue: {
    width: 22,
    textAlign: 'center',
    color: colors.textSecondary,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  arena: {
    flex: 1,
    position: 'relative',
    overflow: 'hidden',
  },
  arenaSkyBack: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
    overflow: 'hidden',
  },
  worldLayer: {
    position: 'absolute',
    left: 0,
    top: 0,
    zIndex: 1,
  },
  arenaSkyBackImage: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: '100%',
    height: '100%',
  },
  platformBg: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
    backgroundColor: 'transparent',
  },
  platformArtClip: {
    position: 'absolute',
    overflow: 'hidden',
    borderRadius: 8,
  },
  platformArtImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  playerWrap: {
    position: 'absolute',
  },
  preMatchOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 40,
    backgroundColor: 'rgba(12, 18, 34, 0.72)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  preMatchLabel: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  preMatchDigit: {
    color: colors.text,
    fontSize: 96,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  gameOverOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 50,
    backgroundColor: 'rgba(12, 18, 34, 0.78)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  gameOverCard: {
    width: '100%',
    maxWidth: 340,
    borderRadius: 16,
    paddingVertical: 22,
    paddingHorizontal: 20,
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.borderStrong,
  },
  gameOverTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: 8,
  },
  gameOverHint: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 20,
  },
  gameOverActions: {
    gap: 10,
  },
  gameOverBtn: {
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  gameOverBtnPrimary: {
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: '#a78bfa',
  },
  gameOverBtnSecondary: {
    backgroundColor: colors.bgElevated,
    borderWidth: 2,
    borderColor: colors.borderStrong,
  },
  gameOverBtnPressed: {
    opacity: 0.88,
  },
  gameOverBtnPrimaryText: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '900',
  },
  gameOverBtnSecondaryText: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
  },
  controlsOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    zIndex: 20,
  },
  controlsTouchLayer: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    zIndex: 20,
    paddingBottom: 0,
  },
  controlsJoystickCluster: {
    alignSelf: 'flex-start',
    paddingTop: 0,
  },
  actionArcWrap: {
    position: 'absolute',
    width: ACTION_ARC_W,
    height: ACTION_ARC_H,
  },
  ctrlBtnOuter: {
    width: ACTION_CIRCLE_SIZE + 8,
    height: ACTION_CIRCLE_SIZE + 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ctrlCircleAbsolute: {
    position: 'absolute',
    overflow: 'visible',
  },
  ctrlRing: {
    position: 'absolute',
    width: ACTION_CIRCLE_SIZE + 8,
    height: ACTION_CIRCLE_SIZE + 8,
    borderRadius: (ACTION_CIRCLE_SIZE + 8) / 2,
    borderWidth: 2,
    opacity: 0.9,
  },
  ctrlRingHit: {
    borderColor: 'rgba(248, 113, 113, 0.55)',
    shadowColor: '#ef4444',
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  ctrlRingDash: {
    borderColor: 'rgba(34, 211, 238, 0.55)',
    shadowColor: '#06b6d4',
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  ctrlRingJump: {
    borderColor: 'rgba(192, 132, 252, 0.55)',
    shadowColor: '#a855f7',
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  ctrlRingCooldown: {
    borderColor: 'rgba(148, 163, 184, 0.5)',
    shadowOpacity: 0.15,
  },
  ctrlCircleGloss: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: '48%',
    backgroundColor: 'rgba(255, 255, 255, 0.14)',
    borderTopLeftRadius: ACTION_CIRCLE_SIZE,
    borderTopRightRadius: ACTION_CIRCLE_SIZE,
  },
  ctrlCircleHit: {
    width: ACTION_CIRCLE_SIZE,
    height: ACTION_CIRCLE_SIZE,
    borderRadius: ACTION_CIRCLE_SIZE / 2,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 1,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.28)',
    backgroundColor: 'rgba(185, 28, 28, 0.88)',
    overflow: 'hidden',
  },
  ctrlCircleDash: {
    width: ACTION_CIRCLE_SIZE,
    height: ACTION_CIRCLE_SIZE,
    borderRadius: ACTION_CIRCLE_SIZE / 2,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 1,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.28)',
    backgroundColor: 'rgba(8, 145, 178, 0.88)',
    overflow: 'hidden',
  },
  ctrlCircleJump: {
    width: ACTION_CIRCLE_SIZE,
    height: ACTION_CIRCLE_SIZE,
    borderRadius: ACTION_CIRCLE_SIZE / 2,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 1,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.28)',
    backgroundColor: 'rgba(109, 40, 217, 0.88)',
    overflow: 'hidden',
  },
  ctrlCircleOnCooldown: {
    backgroundColor: 'rgba(30, 41, 59, 0.92)',
    borderColor: 'rgba(148, 163, 184, 0.35)',
  },
  ctrlCirclePressed: {
    transform: [{ scale: 0.94 }],
  },
  ctrlCooldownVeil: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
  },
  ctrlCooldownSand: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(34, 211, 238, 0.55)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(165, 243, 252, 0.65)',
  },
  ctrlCooldownSeconds: {
    marginTop: 1,
    color: '#f8fafc',
    fontSize: 11,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
    textShadowColor: 'rgba(0,0,0,0.8)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  ctrlBtnDisabled: {
    opacity: 0.5,
  },
  ctrlPressed: { opacity: 0.92 },
  ctrlCircleLabel: {
    color: colors.text,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginTop: -1,
  },
  ctrlCircleSub: {
    color: colors.textSecondary,
    fontSize: 9,
    fontWeight: '900',
    marginTop: 0,
  },
  powerupHudWrap: {
    position: 'absolute',
    top: 8,
    left: 10,
    right: 10,
    zIndex: 12,
    gap: 6,
    alignItems: 'flex-start',
    pointerEvents: 'none',
  },
  powerupPickupToast: {
    alignSelf: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: 'rgba(15, 23, 42, 0.88)',
    borderWidth: 2,
    alignItems: 'center',
    gap: 2,
  },
  powerupPickupToastLabel: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  powerupPickupToastName: {
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 0.3,
  },
  powerupHudChip: {
    minWidth: 148,
    maxWidth: 200,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 10,
    backgroundColor: 'rgba(15, 23, 42, 0.82)',
    borderWidth: 2,
    gap: 5,
  },
  powerupHudChipHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  powerupHudDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  powerupHudName: {
    flex: 1,
    color: colors.text,
    fontSize: 12,
    fontWeight: '900',
  },
  powerupHudTimer: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  powerupHudBarTrack: {
    height: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(148, 163, 184, 0.25)',
    overflow: 'hidden',
  },
  powerupHudBarFill: {
    height: '100%',
    borderRadius: 999,
  },
  lavaLayer: {
    position: 'absolute',
    left: 0,
    zIndex: 25,
    opacity: 1,
    backgroundColor: '#dc2626',
    overflow: 'hidden',
  },
  lavaCrust: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 10,
    backgroundColor: '#f59e0b',
    opacity: 1,
  },
  spectateBanner: {
    position: 'absolute',
    top: 10,
    alignSelf: 'center',
    alignItems: 'center',
    zIndex: 20,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: 'rgba(15, 23, 42, 0.82)',
    borderWidth: 1,
    borderColor: colors.borderStrong,
  },
  spectateBannerText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  spectateBannerHint: {
    color: colors.textMuted,
    fontSize: 10,
    fontWeight: '600',
    marginTop: 2,
  },
  phaseAnnounceOverlay: {
    position: 'absolute',
    top: 10,
    left: 0,
    right: 0,
    zIndex: 18,
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  phaseAnnounceTitle: {
    fontSize: 26,
    fontWeight: '900',
    letterSpacing: 0.8,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.65)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  heroStatsHud: {
    position: 'absolute',
    zIndex: 12,
    flexDirection: 'column',
    gap: 4,
    maxWidth: 168,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(167, 139, 250, 0.35)',
    backgroundColor: 'rgba(15, 23, 42, 0.78)',
    pointerEvents: 'none',
  },
  heroStatsHudTitle: {
    color: '#ddd6fe',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  heroStatsHudItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingVertical: 2,
  },
  heroStatsHudLabel: {
    color: '#e2e8f0',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  heroStatsHudValue: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '800',
    textShadowColor: 'rgba(0, 0, 0, 0.4)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  heroStatsHudBoosted: {
    color: '#4ade80',
  },

    });
}

export type ArenaStyles = ReturnType<typeof createArenaStyles>;
