import { StyleSheet } from 'react-native';
import type { AppColors } from '../../theme/colors';
import { radii, spacing } from '../../theme/tokens';
import { ACTION_ARC_H, ACTION_ARC_W, ACTION_CIRCLE_SIZE } from './constants';

export function createArenaStyles(colors: AppColors) {
    return StyleSheet.create({

  root: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  hud: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    minHeight: 44,
    backgroundColor: colors.bg,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  hudSideLeft: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  hudCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hudSideRight: {
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  hudRightRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  hudPhase: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    textAlign: 'center',
  },
  hudClock: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
    textAlign: 'center',
  },
  hudIconBtn: {
    width: 36,
    height: 36,
    borderRadius: radii.pill,
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.xs,
  },
  hudBtnPressed: { opacity: 0.88 },
  hudHpWrap: {
    width: 124,
  },
  hudHpTrack: {
    height: 8,
    width: '100%',
    borderRadius: 999,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    overflow: 'hidden',
  },
  hudHpFill: {
    height: '100%',
    backgroundColor: colors.success,
  },
  hudHpText: {
    marginTop: 2,
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: '800',
  },
  hudKdText: {
    marginTop: 4,
    color: colors.text,
    fontSize: 11,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
    letterSpacing: 0.3,
  },
  hudTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '900',
    textAlign: 'right',
  },
  devBtn: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: colors.bgElevated,
    borderWidth: 1,
    borderColor: colors.borderStrong,
  },
  devBtnPressed: { opacity: 0.85, transform: [{ scale: 0.98 }] },
  devBtnText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  resetBtn: {
    marginTop: spacing.xs,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: radii.md,
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  resetBtnPressed: {
    opacity: 0.85,
    transform: [{ scale: 0.98 }],
  },
  resetBtnText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    textAlign: 'right',
  },
  arenaFlex: {
    flex: 1,
    overflow: 'visible',
  },
  resultsOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 90,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  venuePvpHoldOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 95,
    backgroundColor: 'rgba(0, 0, 0, 0.62)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  venuePvpHoldCard: {
    width: '100%',
    maxWidth: 380,
    borderRadius: 16,
    paddingVertical: 22,
    paddingHorizontal: 18,
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.borderStrong,
    gap: 12,
  },
  venuePvpHoldTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  venuePvpHoldBody: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 20,
  },
  venuePvpHoldBtn: {
    marginTop: 4,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: '#a78bfa',
  },
  venuePvpHoldBtnText: {
    color: colors.textInverse,
    fontSize: 15,
    fontWeight: '900',
  },
  resultsCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 18,
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.borderStrong,
    gap: 10,
  },
  resultsTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  resultsSubtitle: {
    marginTop: 2,
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    textAlign: 'center',
  },
  resultsTable: {
    marginTop: 4,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.borderStrong,
  },
  resultsTableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 10,
    backgroundColor: colors.bgElevated,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  resultsTableHeaderRow: {
    paddingVertical: 8,
    backgroundColor: colors.surface,
  },
  resultsTableRowLast: {
    borderBottomWidth: 0,
  },
  resultsTh: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  resultsTd: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '800',
  },
  resultsColName: {
    flex: 1,
    minWidth: 0,
    paddingRight: 6,
  },
  resultsColStat: {
    width: 28,
    textAlign: 'center',
  },
  resultsColXp: {
    width: 44,
    textAlign: 'right',
    fontVariant: ['tabular-nums'],
  },
  resultsColResult: {
    width: 52,
    textAlign: 'right',
    fontSize: 11,
    fontWeight: '900',
    color: colors.textSecondary,
  },
  resultsBtn: {
    marginTop: 6,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: '#a78bfa',
  },
  resultsBtnPressed: { opacity: 0.9 },
  resultsBtnText: {
    color: colors.textInverse,
    fontSize: 15,
    fontWeight: '900',
  },
  devPanelOverlay: {
    position: 'absolute',
    left: 12,
    right: 12,
    top: 54,
    zIndex: 80,
  },
  devPanel: {
    padding: 12,
    borderRadius: 14,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.borderStrong,
  },
  devRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  devLabel: {
    flex: 1,
    color: colors.text,
    fontSize: 12,
    fontWeight: '900',
  },
  devChip: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
    minWidth: 88,
    alignItems: 'center',
  },
  devChipOn: {
    backgroundColor: 'rgba(34, 197, 94, 0.14)',
    borderColor: 'rgba(34, 197, 94, 0.45)',
  },
  devChipOff: {
    backgroundColor: 'rgba(148, 163, 184, 0.10)',
    borderColor: 'rgba(148, 163, 184, 0.25)',
  },
  devChipPressed: { opacity: 0.88 },
  devChipText: {
    color: colors.text,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  devStepper: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  devStepBtn: {
    width: 34,
    height: 28,
    borderRadius: 10,
    backgroundColor: colors.bgElevated,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  devStepBtnPressed: { opacity: 0.85 },
  devStepBtnText: { color: colors.text, fontSize: 16, fontWeight: '900' },
  devValue: {
    width: 22,
    textAlign: 'center',
    color: colors.textSecondary,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  arena: {
    flex: 1,
    position: 'relative',
    overflow: 'hidden',
  },
  arenaSkyBack: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
    overflow: 'hidden',
  },
  worldLayer: {
    position: 'absolute',
    left: 0,
    top: 0,
    zIndex: 1,
  },
  arenaSkyBackImage: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: '100%',
    height: '100%',
  },
  platformBg: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
    backgroundColor: 'transparent',
  },
  platformArtClip: {
    position: 'absolute',
    overflow: 'hidden',
    borderRadius: 8,
  },
  platformArtImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  playerWrap: {
    position: 'absolute',
  },
  preMatchOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 40,
    backgroundColor: 'rgba(12, 18, 34, 0.72)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  preMatchLabel: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  preMatchDigit: {
    color: colors.text,
    fontSize: 96,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  gameOverOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 50,
    backgroundColor: 'rgba(12, 18, 34, 0.78)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  gameOverCard: {
    width: '100%',
    maxWidth: 340,
    borderRadius: 16,
    paddingVertical: 22,
    paddingHorizontal: 20,
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.borderStrong,
  },
  gameOverTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: 8,
  },
  gameOverHint: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 20,
  },
  gameOverActions: {
    gap: 10,
  },
  gameOverBtn: {
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  gameOverBtnPrimary: {
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: '#a78bfa',
  },
  gameOverBtnSecondary: {
    backgroundColor: colors.bgElevated,
    borderWidth: 2,
    borderColor: colors.borderStrong,
  },
  gameOverBtnPressed: {
    opacity: 0.88,
  },
  gameOverBtnPrimaryText: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '900',
  },
  gameOverBtnSecondaryText: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
  },
  controlsOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    zIndex: 20,
  },
  controlsJoystickCluster: {
    alignSelf: 'flex-start',
    paddingLeft: 28,
    paddingTop: 0,
  },
  actionArcWrap: {
    position: 'absolute',
    width: ACTION_ARC_W,
    height: ACTION_ARC_H,
  },
  ctrlCircleAbsolute: {
    position: 'absolute',
    overflow: 'hidden',
  },
  ctrlCircleGloss: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: '52%',
    backgroundColor: 'rgba(255, 255, 255, 0.10)',
  },
  ctrlCircleHit: {
    width: ACTION_CIRCLE_SIZE,
    height: ACTION_CIRCLE_SIZE,
    borderRadius: ACTION_CIRCLE_SIZE / 2,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    backgroundColor: 'rgba(220, 38, 38, 0.72)',
    shadowColor: colors.text,
    shadowOpacity: 0.4,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 10,
  },
  ctrlCircleDash: {
    width: ACTION_CIRCLE_SIZE,
    height: ACTION_CIRCLE_SIZE,
    borderRadius: ACTION_CIRCLE_SIZE / 2,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    backgroundColor: 'rgba(14, 116, 144, 0.72)',
    shadowColor: colors.text,
    shadowOpacity: 0.4,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 10,
  },
  ctrlCircleJump: {
    width: ACTION_CIRCLE_SIZE,
    height: ACTION_CIRCLE_SIZE,
    borderRadius: ACTION_CIRCLE_SIZE / 2,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    backgroundColor: 'rgba(91, 33, 182, 0.72)',
    shadowColor: colors.text,
    shadowOpacity: 0.4,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 10,
  },
  ctrlBtnDisabled: {
    opacity: 0.45,
  },
  ctrlPressed: { opacity: 0.85, transform: [{ scale: 0.98 }] },
  ctrlCircleLabel: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  ctrlCircleSub: {
    color: colors.textSecondary,
    fontSize: 9,
    fontWeight: '900',
    marginTop: 0,
  },
  powerupHudWrap: {
    position: 'absolute',
    top: 8,
    left: 10,
    right: 10,
    zIndex: 12,
    gap: 6,
    alignItems: 'flex-start',
  },
  powerupPickupToast: {
    alignSelf: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: 'rgba(15, 23, 42, 0.88)',
    borderWidth: 2,
    alignItems: 'center',
    gap: 2,
  },
  powerupPickupToastLabel: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  powerupPickupToastName: {
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 0.3,
  },
  powerupHudChip: {
    minWidth: 148,
    maxWidth: 200,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 10,
    backgroundColor: 'rgba(15, 23, 42, 0.82)',
    borderWidth: 2,
    gap: 5,
  },
  powerupHudChipHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  powerupHudDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  powerupHudName: {
    flex: 1,
    color: colors.text,
    fontSize: 12,
    fontWeight: '900',
  },
  powerupHudTimer: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  powerupHudBarTrack: {
    height: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(148, 163, 184, 0.25)',
    overflow: 'hidden',
  },
  powerupHudBarFill: {
    height: '100%',
    borderRadius: 999,
  },
  lavaLayer: {
    position: 'absolute',
    left: 0,
    zIndex: 25,
    opacity: 1,
    backgroundColor: '#dc2626',
    overflow: 'hidden',
  },
  lavaCrust: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 10,
    backgroundColor: '#f59e0b',
    opacity: 1,
  },
  spectateBanner: {
    position: 'absolute',
    top: 10,
    alignSelf: 'center',
    alignItems: 'center',
    zIndex: 20,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: 'rgba(15, 23, 42, 0.82)',
    borderWidth: 1,
    borderColor: colors.borderStrong,
  },
  spectateBannerText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  spectateBannerHint: {
    color: colors.textMuted,
    fontSize: 10,
    fontWeight: '600',
    marginTop: 2,
  },
  phaseAnnounceOverlay: {
    position: 'absolute',
    top: 10,
    left: 0,
    right: 0,
    zIndex: 18,
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  phaseAnnounceTitle: {
    fontSize: 26,
    fontWeight: '900',
    letterSpacing: 0.8,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.65)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  heroStatsHud: {
    position: 'absolute',
    right: 8,
    top: 8,
    zIndex: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    maxWidth: '58%',
    justifyContent: 'flex-end',
  },
  heroStatsHudItem: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: 'rgba(15, 23, 42, 0.78)',
  },
  heroStatsHudLabel: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  heroStatsHudValue: {
    color: colors.text,
    fontSize: 11,
    fontWeight: '800',
  },
  heroStatsHudBoosted: {
    color: '#4ade80',
  },

    });
}

export type ArenaStyles = ReturnType<typeof createArenaStyles>;
